name: Publish Package
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # 升级到最新版本
      - uses: actions/setup-node@v3
        with:
          node-version: '18'  # 建议升级到 Node.js 18+
          registry-url: 'https://registry.npmjs.org'
          scope: '@zyileven'  # 修改为你的作用域（如果包名是作用域包）
      - run: npm ci && npm run build
      - name: Configure npm auth
        run: |
          echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          # 如果是作用域包，取消下方注释
          # echo "@zyileven:registry=https://registry.npmjs.org/" >> .npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm publish --access public  # 如果首次发布或作用域包需要 public